// ─── Report builder ──────────────────────────────────────────────────────────
// Turns computed analytics into a structured, policy-grade Report object and a
// downloadable markdown rendering.

import type {
  Report,
  ReportSection,
  PolicyRecommendation,
} from "./types";

export function reportToMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(`# ${r.headline}`);
  lines.push("");
  lines.push(`> **Question:** ${r.question}`);
  lines.push(
    `> Generated ${r.generatedAt} · analysis type: **${r.request.analysisType}** · domain: **${r.request.domain}** · request parsed by: ${r.request.source}`
  );
  lines.push("");
  lines.push("## Executive summary");
  lines.push(r.executiveSummary);
  lines.push("");

  for (const s of r.sections) {
    lines.push(`## ${s.heading}`);
    if (s.body) lines.push(s.body);
    if (s.table) {
      lines.push("");
      lines.push(`| ${s.table.columns.join(" | ")} |`);
      lines.push(`| ${s.table.columns.map(() => "---").join(" | ")} |`);
      for (const row of s.table.rows)
        lines.push(`| ${row.join(" | ")} |`);
    }
    lines.push("");
  }

  if (r.recommendations.length) {
    lines.push("## Policy recommendations");
    r.recommendations.forEach((rec, i) => {
      lines.push(`### Recommendation ${i + 1}: ${rec.decision}`);
      lines.push(`- **Evidence:** ${rec.evidence}`);
      lines.push(`- **Cost:** ${rec.cost}`);
      lines.push(`- **Benefit:** ${rec.benefit}`);
      lines.push(`- **Risks:** ${rec.risks}`);
      lines.push(`- **Monitoring:** ${rec.monitoring}`);
      lines.push("");
    });
  }

  lines.push("## Methods used");
  lines.push(r.methodsUsed.map((m) => `- ${m}`).join("\n"));
  lines.push("");
  lines.push("## Limitations & uncertainty");
  lines.push(r.limitations.map((l) => `- ${l}`).join("\n"));
  lines.push("");
  lines.push(
    "---\n*Generated by PHDAROP — Public Health Decision Analytics. " +
      "Analytical core is deterministic and reproducible; figures are computed, not estimated by a language model. " +
      "Validate context-specific parameters before policy use.*"
  );
  return lines.join("\n");
}

export function section(
  heading: string,
  body: string,
  table?: ReportSection["table"]
): ReportSection {
  return { heading, body, table };
}

export function recommendation(
  r: PolicyRecommendation
): PolicyRecommendation {
  return r;
}

export const STANDARD_LIMITATIONS = [
  "Demonstration scenarios use calibrated illustrative parameters; replace with the Master Analytical Database (HMIS/NFHS/GBD/programme data) before real allocation decisions.",
  "Optimization assumes point parameters in this view; the production engine propagates the full Bayesian burden posterior (stochastic/robust optimization).",
  "Effectiveness and cost are context-dependent; localize before acting.",
  "Equity weights are normative and should be set through a deliberative process with an explicit floor.",
];
