import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "PHDAROP — Public Health Decision Analytics",
  description:
    "Prompt-driven, policy-grade decision analytics and resource optimization for public health. Ask a question; get a computed, reproducible report.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="site-header">
          <div className="wrap">
            <span className="brand">PHDAROP</span>
            <span className="brand-sub">Public Health Decision Analytics</span>
            <nav>
              <a
                href="https://github.com"
                target="_blank"
                rel="noreferrer"
                className="nav-link"
              >
                Docs · GitHub
              </a>
            </nav>
          </div>
        </header>
        <main className="wrap">{children}</main>
        <footer className="site-footer">
          <div className="wrap">
            Analytical core is deterministic &amp; reproducible — figures are
            computed, not generated by a language model. Validate
            context-specific parameters before policy use.
          </div>
        </footer>
      </body>
    </html>
  );
}
